```yaml
name: Build Astro and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight (UTC)


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Download Generated Markdown
      uses: actions/download-artifact@v3
      with:
        name: app-markdown
        path: public/config

    - name: Build Astro Site
      run: npm run astro build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        force_orphan: true
```
